name: sidewalk-validator-ai
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.1=h7b32b05_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - accelerate==1.10.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blinker==1.9.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.2.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.2.0
      - datasets==4.0.0
      - decorator==5.2.1
      - dill==0.3.8
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.1.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - narwhals==2.0.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - open3d==0.18.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotly==6.2.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.4
      - retrying==1.4.1
      - rpds-py==0.26.0
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.55.0
      - triton==3.3.1
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /gscratch/scrubbed/jsomeara/envs/sidewalk-validator-ai
